# .logan.yaml configures the logan tool to run terraform
version: "1.2"
project: "{{ cookiecutter.product_slug }}"
image: "registry.gitlab.developers.cam.ac.uk/uis/devops/infra/dockerimages/logan-terraform:1.3"
mount_docker_socket: true
use_impersonation: true
